[2022-07-29 18:28:54,327] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dataperf.create-baselines manual__2022-07-29T18:28:52.910257+00:00 [queued]>
[2022-07-29 18:28:54,334] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dataperf.create-baselines manual__2022-07-29T18:28:52.910257+00:00 [queued]>
[2022-07-29 18:28:54,335] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-29 18:28:54,335] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-07-29 18:28:54,335] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-29 18:28:54,348] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): create-baselines> on 2022-07-29 18:28:52.910257+00:00
[2022-07-29 18:28:54,352] {standard_task_runner.py:52} INFO - Started process 110 to run task
[2022-07-29 18:28:54,354] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dataperf', 'create-baselines', 'manual__2022-07-29T18:28:52.910257+00:00', '--job-id', '181', '--raw', '--subdir', 'DAGS_FOLDER/dataperfr.py', '--cfg-path', '/tmp/tmp1lf1zx03', '--error-file', '/tmp/tmp12as3nll']
[2022-07-29 18:28:54,355] {standard_task_runner.py:80} INFO - Job 181: Subtask create-baselines
[2022-07-29 18:28:54,406] {task_command.py:371} INFO - Running <TaskInstance: dataperf.create-baselines manual__2022-07-29T18:28:52.910257+00:00 [running]> on host 54cc325577cf
[2022-07-29 18:28:54,466] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dataperf
AIRFLOW_CTX_TASK_ID=create-baselines
AIRFLOW_CTX_EXECUTION_DATE=2022-07-29T18:28:52.910257+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-29T18:28:52.910257+00:00
[2022-07-29 18:28:54,468] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-07-29 18:28:54,469] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python dependency/create_baselines.py']
[2022-07-29 18:28:54,477] {subprocess.py:85} INFO - Output:
[2022-07-29 18:28:54,548] {subprocess.py:92} INFO - python: can't open file 'dependency/create_baselines.py': [Errno 2] No such file or directory
[2022-07-29 18:28:54,550] {subprocess.py:96} INFO - Command exited with return code 2
[2022-07-29 18:28:54,561] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2022-07-29 18:28:54,564] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=dataperf, task_id=create-baselines, execution_date=20220729T182852, start_date=20220729T182854, end_date=20220729T182854
[2022-07-29 18:28:54,575] {standard_task_runner.py:97} ERROR - Failed to execute job 181 for task create-baselines (Bash command failed. The command returned a non-zero exit code 2.; 110)
[2022-07-29 18:28:54,607] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-29 18:28:54,641] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
