[2022-07-29 18:37:04,660] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dataperf.create-baselines manual__2022-07-29T18:37:03.641489+00:00 [queued]>
[2022-07-29 18:37:04,669] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dataperf.create-baselines manual__2022-07-29T18:37:03.641489+00:00 [queued]>
[2022-07-29 18:37:04,670] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-29 18:37:04,670] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-07-29 18:37:04,671] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-29 18:37:04,686] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): create-baselines> on 2022-07-29 18:37:03.641489+00:00
[2022-07-29 18:37:04,691] {standard_task_runner.py:52} INFO - Started process 83 to run task
[2022-07-29 18:37:04,695] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dataperf', 'create-baselines', 'manual__2022-07-29T18:37:03.641489+00:00', '--job-id', '187', '--raw', '--subdir', 'DAGS_FOLDER/dataperfr.py', '--cfg-path', '/tmp/tmpgvhtybud', '--error-file', '/tmp/tmphb_z5cgl']
[2022-07-29 18:37:04,695] {standard_task_runner.py:80} INFO - Job 187: Subtask create-baselines
[2022-07-29 18:37:04,755] {task_command.py:371} INFO - Running <TaskInstance: dataperf.create-baselines manual__2022-07-29T18:37:03.641489+00:00 [running]> on host 54cc325577cf
[2022-07-29 18:37:04,824] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dataperf
AIRFLOW_CTX_TASK_ID=create-baselines
AIRFLOW_CTX_EXECUTION_DATE=2022-07-29T18:37:03.641489+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-29T18:37:03.641489+00:00
[2022-07-29 18:37:04,826] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-07-29 18:37:04,827] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python dags/dependency/create_baselines.py']
[2022-07-29 18:37:04,836] {subprocess.py:85} INFO - Output:
[2022-07-29 18:37:04,915] {subprocess.py:92} INFO - python: can't open file 'dags/dependency/create_baselines.py': [Errno 2] No such file or directory
[2022-07-29 18:37:04,918] {subprocess.py:96} INFO - Command exited with return code 2
[2022-07-29 18:37:04,932] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2022-07-29 18:37:04,936] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=dataperf, task_id=create-baselines, execution_date=20220729T183703, start_date=20220729T183704, end_date=20220729T183704
[2022-07-29 18:37:04,951] {standard_task_runner.py:97} ERROR - Failed to execute job 187 for task create-baselines (Bash command failed. The command returned a non-zero exit code 2.; 83)
[2022-07-29 18:37:04,988] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-29 18:37:05,037] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
