[2022-07-29 22:17:21,548] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dataperf.create-baselines manual__2022-07-29T22:17:20.244866+00:00 [queued]>
[2022-07-29 22:17:21,562] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dataperf.create-baselines manual__2022-07-29T22:17:20.244866+00:00 [queued]>
[2022-07-29 22:17:21,563] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-29 22:17:21,564] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-07-29 22:17:21,564] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-29 22:17:21,579] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): create-baselines> on 2022-07-29 22:17:20.244866+00:00
[2022-07-29 22:17:21,583] {standard_task_runner.py:52} INFO - Started process 146 to run task
[2022-07-29 22:17:21,588] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dataperf', 'create-baselines', 'manual__2022-07-29T22:17:20.244866+00:00', '--job-id', '218', '--raw', '--subdir', 'DAGS_FOLDER/dataperfr.py', '--cfg-path', '/tmp/tmpbydmbg_u', '--error-file', '/tmp/tmpj22_fhdb']
[2022-07-29 22:17:21,588] {standard_task_runner.py:80} INFO - Job 218: Subtask create-baselines
[2022-07-29 22:17:21,661] {task_command.py:371} INFO - Running <TaskInstance: dataperf.create-baselines manual__2022-07-29T22:17:20.244866+00:00 [running]> on host 5eb1407492fa
[2022-07-29 22:17:21,908] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dataperf
AIRFLOW_CTX_TASK_ID=create-baselines
AIRFLOW_CTX_EXECUTION_DATE=2022-07-29T22:17:20.244866+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-29T22:17:20.244866+00:00
[2022-07-29 22:17:21,909] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-07-29 22:17:21,910] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python /opt/***/dags/dependency/create_baselines.py']
[2022-07-29 22:17:21,923] {subprocess.py:85} INFO - Output:
[2022-07-29 22:17:25,547] {subprocess.py:92} INFO - Traceback (most recent call last):
[2022-07-29 22:17:25,547] {subprocess.py:92} INFO -   File "/opt/***/dags/dependency/create_baselines.py", line 22, in <module>
[2022-07-29 22:17:25,548] {subprocess.py:92} INFO -     with open("task_setup.yml", "r") as f:
[2022-07-29 22:17:25,548] {subprocess.py:92} INFO - FileNotFoundError: [Errno 2] No such file or directory: 'task_setup.yml'
[2022-07-29 22:17:25,867] {subprocess.py:96} INFO - Command exited with return code 1
[2022-07-29 22:17:25,881] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-07-29 22:17:25,885] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=dataperf, task_id=create-baselines, execution_date=20220729T221720, start_date=20220729T221721, end_date=20220729T221725
[2022-07-29 22:17:25,903] {standard_task_runner.py:97} ERROR - Failed to execute job 218 for task create-baselines (Bash command failed. The command returned a non-zero exit code 1.; 146)
[2022-07-29 22:17:25,938] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-29 22:17:25,987] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
